[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

# MAKES COMPILATION VERY SLOW!!
viaIR = true # ir optimizer 

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

